### ISSUE TITLE
making it possible to infer readers/writers between scripts?

### ISSUE THREAD

**Issue by deanmalmgren** [deanmalmgren/flo#25]
This is probably something for down the road --- if ever--- but it could be useful to be able to infer the reader/writer you need based on the upstream output. This might require a user to specify the output schema in the workflow.yaml, but could definitely reduce the amount of code you need to write to create workflows. 

For example, if you have a workflow like this:

``` yaml

---
creates: data/raw.csv
depends: src/run_simulation.py
output_schema: [int, float, float, str]
command: python {{depends}} > {{creates}}

---
creates: data/pdf.dat
depends: 
  - src/pdf.py
  - data/raw.csv
output_schema: [float, float]
command: python {{depends|join(' ')}} > {{creates}}
```

Then in the `src/run_simulation.py`, you could do something like this, which would auto-infer the writer format to use based on the filename and the `output_schema` specified in the workflow.

``` python
from workflow.io import get_writer
writer = get_writer()
for row in result:
    writer.writerow(row)
```

Similarly for the next item in the pipeline. `src/pdf.py` could infer the reader based on its `depends` and infer the writer from the `output_schema` declaration specified in the workflow.

``` python
from workflow.io import get_reader, get_writer
reader = get_reader()
in_data = [row[1] for row in reader]
output = calculate_pdf(in_data)
writer= get_writer()
for row in output:
    writer.writerow(row)
```
