### ISSUE TITLE
Workflow does not recognize a change to a file

### ISSUE THREAD

**Issue by ahwolf** [deanmalmgren/flo#35]
```
# This is an attempt to use the workflow
# We will first try to get the list of S&P 500 companies from wikipedia
# parse the data and save into mysql





# trying to use a variable

---
input_name: data/sp500.html


tasks:
# create some data to analyze.
  -
    creates: data/sp500.html
    command:
      - mkdir -p $(dirname {{creates}})
      - wget http://en.wikipedia.org/wiki/List_of_S%26P_500_companies -O {{creates}}
    alias: get_data

  # extract the data
  -
    creates: data/sp500.csv
    depends: data/sp500.html
    command: python Code/parse_sp500.py data/sp500.html {{creates}}

  # get 90 day json_dumps
  -
    creates: data/daily_trends/dump/
    depends: data/sp500.csv
    command:
      - mkdir -p {{creates}}
      - python Code/get_trends.py data/sp500.csv

  # convert dumps to csv
```

When I change get_trends.py and then type `workflow --dry-run` it outputs: No tasks are out of sync in the workflow defined in 'workflow.yaml'

**Comment by deanmalmgren** [comment]
Noticed this when we were pairing yesterday but not when you first posted this. To make sure workflow knows to track `Code/get_trends.py`, you have to add it as a `depends` like this:

``` yaml
# >< SNIP ><
  -
    creates: data/daily_trends/dump/
    depends: 
      - Code/get_trends.py
      - data/sp500.csv
    command:
      - mkdir -p {{creates}}
      - python {{depends|join(' ')}}
```

I'd also recommend using the `depends` declaration when you actually call the script so that you aren't repeating information (the `{{depends|join(' ')}}` part above).
